### ISSUE TITLE
Cannot read propert 'emit' of null

### ISSUE THREAD

**Issue by tomitrescak** [mthuret/storybook-addon-specifications#1]
Hi, I have setup the project according to instructions, but am getting following error:

```
Cannot read property 'emit' of null
TypeError: Cannot read property 'emit' of null
    at specs (webpack:///~/storybook-addon-specifications/dist/preview.js:26:10)
    at eval (webpack:///imports/client/modules/notifications/components/stories/notification_stories.jsx:24:45)
    at renderMain (webpack:///~/@kadira/storybook/dist/client/preview/render.js:86:38)
    at renderPreview (webpack:///~/@kadira/storybook/dist/client/preview/render.js:101:10)
    at Array.renderUI (webpack:///~/@kadira/storybook/dist/client/preview/index.js:81:26)
    at Object.dispatch (webpack:///~/redux/lib/createStore.js:186:19)
    at PageBus.eval (webpack:///~/@kadira/storybook/dist/client/preview/page_bus.js:60:27)
    at PageBus.EventEmitter.emit (webpack:///~/events/events.js:81:17)
    at eval (webpack:///~/page-bus/index.js:21:44)
```

any idea? Thanks!

**Comment by tomitrescak** [comment]
after i installed @kadira/storybook-addons all worked well.

**Comment by arunoda** [comment]
@tomitrescak Are you using NPM2 or NPM3?
