### ISSUE TITLE
Unable to make CI run

### ISSUE THREAD

**Issue by tomitrescak** [mthuret/storybook-addon-specifications#3]
Thanks for this fantastic addition! This makes so much sense doing it the way you did. Hi, I'm not sure what I'm doing wrong, but am getting following error when I am using mocha to run my tests:

```
Error: dataId is not supplied via queryString
    at Object.<anonymous> (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/@kadira/storybook/dist/client/preview/index.js:64:11)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/@kadira/storybook/dist/client/index.js:26:16)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (notification_stories.jsx:2:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomi/Github/apps/temp/ClaraWeb/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/mocha/lib/mocha.js:469:10)
    at loadAndRun (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/mocha/bin/_mocha:360:22)
    at Object.<anonymous> (/Users/tomi/Github/apps/temp/ClaraWeb/node_modules/mocha/bin/_mocha:377:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by tomitrescak** [comment]
Ok, it was the extra storybook references in the project. 

Last issue seems to be that tests are not executed when running mocha .. how did you achieve that tests are called from stories ?

**Comment by mthuret** [comment]
This part is the one that unfortunately for now requires some modification of your configuration. I try to describe the step in the Readme, did you follow it ? 

Basically you'll need to indicate that when it's mocha that run the test, it actually use the describe and it mocha implementation. If you clone this addon repo, you'll find an example that you can execute. 

-> package.json for the script command line.
-> .storybook (__conf__, __tests__, __mock__), to see everything.

**Comment by tomitrescak** [comment]
@mthuret If you change the facade to this, you do not need to change the code.

```js
import { describe as mochaDescribe, it as mochaIt } from 'mocha';

export const storiesOf = function storiesOf() {
  console.log('executing ...')
  var api = {};
  api.add = (name, func)=> { 
    func();
    return api; 
  };
  api.addWithInfo = (name, func)=> { 
    func();
    return api; 
  };
  return api;
};
export const action = () => {};

export const linkTo = () => {};

export const specs = (spec) => {
  spec();
};

export const describe = mochaDescribe;
export const it = mochaIt;
```

It will execute specs from within stories. What do you think?

**Comment by mthuret** [comment]
I think that's great :) I'll try this later and update the repo as well.

**Comment by tomitrescak** [comment]
I still cannot make this work with storybook as I'm getting storiesOf is not defined. I'll post back if I'll solve it. For some reason I cannot inject storiesOf reference into global scope. If I do that at webpack level it crashes storybook with `dataId is not supplied via queryString`.

**Comment by mthuret** [comment]
Using your mock file, I was able to make it work correctly. 

I made a new release, so you can see it live. 
I'm using the global describe and it when using mocha. (not importing it)
