### ISSUE TITLE
Prohibits use of addon react-storybook-addon-info

### ISSUE THREAD

**Issue by tomitrescak** [mthuret/storybook-addon-specifications#5]
When used with the "info" addon, following error is produced:

```
warning.js:44 Warning: exception thrown by devtool while handling onSetChildren: Invariant Violation: Expected onSetParent() and onSetChildren() to be consistent (4 has parents 3 and 2).
Invariant Violation: Expected onSetParent() and onSetChildren() to be consistent (4 has parents 3 and 2).
    at invariant (http://localhost:9001/static/webpack:/~/fbjs/lib/invariant.js:38:15)
    at http://localhost:9001/static/webpack:/~/react/lib/ReactComponentTreeDevtool.js:89:80
    at Array.forEach (native)
    at http://localhost:9001/static/webpack:/~/react/lib/ReactComponentTreeDevtool.js:77:20
    at updateTree (http://localhost:9001/static/webpack:/~/react/lib/ReactComponentTreeDevtool.js:38:3)
    at Object.onSetChildren (http://localhost:9001/static/webpack:/~/react/lib/ReactComponentTreeDevtool.js:74:5)
    at http://localhost:9001/static/webpack:/~/react/lib/ReactDebugTool.js:30:37
    at Array.forEach (native)
    at emitEvent (http://localhost:9001/static/webpack:/~/react/lib/ReactDebugTool.js:27:17)
    at Object.onSetChildren (http://localhost:9001/static/webpack:/~/react/lib/ReactDebugTool.js:270:5)
```

**Comment by mthuret** [comment]
Can you try to update the version of the info-addon plugin ? 
Using 3.2.1, I manage to have this example working (that you can also try with your project) 

```js
stories.addWithInfo('Hello World',
  `
      This is the basic usage with the button with providing a label to show the text.
    `,
  () => {
  const helloWorldStory =
    <button onClick={action('Hello World')}>
      Hello World
    </button>;

  specs(() => describe('Hello World', function () {
    it('Should have the Hello World label', function () {
      let output = mount(helloWorldStory);
      expect(output.text()).toContain('Hello World');
    });
  }));
  return helloWorldStory;
},
  { inline: true }
);
```

**Comment by mthuret** [comment]
@tomitrescak : Did you manage to make your use case work ?

**Comment by tomitrescak** [comment]
Yes! Thanks, it works now ;) One thing would also be great is to disable the CAPITALS, it is difficult to read it, mostly when I am comparing strings. But I'll close this one. Thanks for your help!

**Comment by mthuret** [comment]
Yes, i see what you mean. I remove the uppercase and release a new version (1.0.14)
